name: Build
on: [push, pull_request]

jobs:
  build:
    name: Test Conda (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: ["ubuntu-latest"]
  
    steps:
    
      - name: Get Conda
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      
      - name: Install spring
        shell: bash -l {0}
        run: |
          conda install -c bioconda spring

      - name: Conda list
        shell: bash -l {0}
        run: conda list

      - name: Test Spring
        shell: bash -l {0}
        run: |
          spring
  